name: CI
on:
  push:
  pull_request:

jobs:
  npm-test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '14' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
      - run: npm install coveralls
      - run: npm run coverage > lcov.info
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
